### ISSUE TITLE
more useful name and description would be a good idea =)

### ISSUE THREAD

**Issue by taylor-bsg** [matthewdh7/vlsi3#2]

**Comment by taylor-bsg** [comment]
@matthewdh7

**Comment by taylor-bsg** [comment]
Maybe some docs as well

**Comment by matthewdh7** [comment]
name and readme updated! with link to full report for details

**Comment by taylor-bsg** [comment]
![Screen Shot 2024-06-11 at 6 27 31 PM](https://github.com/matthewdh7/VectorMatrix_Accelerator/assets/17460864/cc850d01-3eb1-42a2-b96e-17ea1fe3aa08)

**Comment by matthewdh7** [comment]
oh got it, fixed
